### ISSUE TITLE
[fix/common] categoryItem 컴포넌트

### ISSUE THREAD

**Issue by YuHyun-P** [prgrms-web-devcourse/Team-Meoguri-Linkocean-FE#124]
# 개요

- #106 컴포넌트에서 이상하게 동작하는 점 수정
  - `checked` 대신 `on` prop 사용할 시 상태가 느리게 반영되는 건지 반영이 안 되는 건지 미지수

**Comment by YuHyun-P** [comment]
To. 나디아 @NamgyungKim 

```ts
// selectCategoryModal.tsx
{CATEGORY.map((category) => (
  <CategoryItem
    name={category}
    onChange={handleCategoryClick}
    // checked={favoriteCategories.includes(category)}
    on={favoriteCategories.includes(category)}
    key={category}
  />
))}
```

```ts
// categoryItem.tsx
const CategoryItem = ({ name, on, onChange, ...props }: CategoryItemProps) => {
  const [checked, toggle] = useToggle(on);
  const { color, fileName } = CATEGORY_MAP[name];
  const imgSrc = `/icon/category/${fileName}${checked ? "-selected" : ""}.svg`;

  console.log(name, "상태값", checked, "초기값", on);
  ...
```
위 코드로 아래의 순서대로 동작하면서 console을 살펴본 결과, 
(초기 조건: IT가 기본값으로 선택되어있는 상황)

1) `selectedModalCategory`를 열기
![첫렌더링](https://user-images.githubusercontent.com/96400112/183258425-ff8fa0b1-0bde-483a-907f-2d3e671d8cac.PNG)

2) "요리" 카테고리 선택
![요리선택](https://user-images.githubusercontent.com/96400112/183258453-15e47362-4e16-48b9-bc05-f62e2340e252.PNG)

3) `선택취소` 버튼 클릭
![선택취소](https://user-images.githubusercontent.com/96400112/183258469-c9e59bb7-b630-404a-9b57-fd290b786133.PNG)

⇒ 아래 "요리"의 상태값과 초기값 변화를 보면, 3) `선택취소` 버튼 클릭 시 요리 초기값은 false이지만, 상태값이 true임을 알 수 있습니다. 

```
1) 요리 상태값 false 초기값 false
2) 요리 상태값 true 초기값 true 
3) 요리 상태값 true 초기값 false
```

추론한 결과로는 모달이기 때문에 모달 내 categoryItem들의 초기값이 `favoriteCategories.includes(category)`값으로 변경되고 있지만, **첫 렌더링** 때에만 초기값으로 `categoryItem` 컴포넌트의 상태값이 초기화 되는 것 같습니다. 이후에는 리렌더링이라 초기값으로 넘겨주는 `on`값만 변경되고 `categoryItem` 컴포넌트의 상태값이 초기화 되지 않는 것 같습니다. 
그래서 그 때 얘기한 모달이 켜질 때에만 렌더링되도록 변경해봤습니다.

```ts
{ isShowModal ? (<Modal ...> .... </Modal>) : null }
```
![meoguri](https://user-images.githubusercontent.com/96400112/183259064-f43b2353-8484-4ad1-afcb-ca99ea2c815c.gif)

잘 동작합니다..!
기존 코드에서는 모달을 떠있지 않은 상태여도 상태값이 변경될 때마다 콘솔이 계속 찍혔는데, 위 코드로 변경했더니 `카테고리 선택` 버튼을 클릭해야만 콘솔이 찍히고 있어 더 괜찮아 보입니다(?)

그래서 제 생각에는 categoryItem에는 문제라기 보다는 모달 때문에 생각과 다르게 동작하는 것 같습니다. `isShowModal` 값에 따라서 `Modal`을 선택적 렌더링하도록 해결하는 건 어떻게 생각하시나용?

**Comment by NamgyungKim** [comment]
말씀하신 방법대로 고쳐서 pr 올리겠습니다~~
수고하셨습니다😀😀
