### ISSUE TITLE
[refactor/common] 리팩터링

### ISSUE THREAD

**Issue by NamgyungKim** [prgrms-web-devcourse/Team-Meoguri-Linkocean-FE#159]
# 개요
리팩터링 기간에 수정할 사항들

# 작업사항
- [ ] pageLayout 컴포넌트(반응형)
- [ ] page 컴포넌트 파일명 변경 및 컴포넌트 쪼개기
- [ ] footer 
- [ ] '/' 메인에 사이트 정보
- [ ] meta 태그

**Comment by YuHyun-P** [comment]
![image](https://user-images.githubusercontent.com/96400112/183536535-25dd67cf-e710-4a5c-b1d8-243d1cb53705.png)

![image](https://user-images.githubusercontent.com/96400112/183536800-7ff8f9c4-90a4-45ec-847f-f411cdf0902a.png)

url 길어지면 업데이트 날짜도 줄어드는데 다른 좋은 방법이 없을까요!

**Comment by NamgyungKim** [comment]
날짜부분의 넓이를 고정하면 괜찮을 것 같습니다. ~
url은 너무 긴것도 있어서 말줄임을 해야할 것 같습니다.
