### ISSUE TITLE
[fix/404] UI 개선

### ISSUE THREAD

**Issue by jieun0411** [prgrms-web-devcourse/Team-Meoguri-Linkocean-FE#244]
# 개요
최선을 다해 기깔나게 만들어보겠습니다.

# 작업사항

**_before_**
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/67778677/184178444-7ef6d917-6ae6-4425-a503-8f2f69c6bcb5.png">

**_after_**
<img width="906" alt="image" src="https://user-images.githubusercontent.com/67778677/184178658-fec5b9ea-2d19-4f3d-9220-6163011784ad.png">

**Comment by NamgyungKim** [comment]
기대기대~!
